### ISSUE TITLE
Create website for docs instead of raw markdown pages

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#255]
Decided on using mkdocs with material theme with @electrum and all members at dev sync

```[tasklist]
### Tasks
- [ ] mkdocs site
- [ ] material theme
- [ ] use logos
- [ ] separate sections for developers and users
- [ ] theme similar to trino.io maybe
- [ ] automatic push to separate branch via gha run on merge to main
```

**Comment by mosabua** [comment]
using this theme - check for CI and GH pages setup - https://github.com/squidfunk/mkdocs-material

and look and feel and more

https://squidfunk.github.io/mkdocs-material/

**Comment by mosabua** [comment]
We can make it much better looking and importantly much better organized and usable. We also get search and so on.

**Comment by ebyhr** [comment]
@andythsu It's not "moving". We still can see the raw markdown rendered by GitHub.

**Comment by mosabua** [comment]
That too @ebyhr ... but over the site will be much better.. also the navigation on the raw markdown source goes away..
