### ISSUE TITLE
Ensure consistent project name usage

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#39]
Approved and agreed upon names are 

* "Trino Gateway" overall
* "trino-gateway" for repository and similar technical usage
* "io.trino.gateway.*" as Java package, groupId and similar namespace usage

```[tasklist]
### Tasks
- [x] Review and update documentation
- [x] Review and update readme  (maybe adding this info there..)
- [x] Review and update source code and inline javadoc
- [x] Change title in web user interface
```

**Comment by mosabua** [comment]
I am gonna call this done. If we find more instances of wrong naming we can fix on the go.
