### ISSUE TITLE
Add container

### ISSUE THREAD

**Issue by mosabua** [trinodb/trino-gateway#86]
Besides the executable JAR we should at least provide a container image to run Trino Gateway.

```[tasklist]
### Tasks
- [x] Add separate folder and Maven module to build docker container
- [x] Add release step to publish container
- [x] Update documentation to add how to run with Docker container and custom config
```

**Comment by rdsarvar** [comment]
Hi @mosabua, are we looking to have the gateway follow the same release strategy as the core Trino repository? Do you happen to have a link to any docs/runbooks/etc which detail how the existing releases are done?

(I've seen https://github.com/trinodb/trino/tree/master/core/docker but was curious to where the building and releasing of the images actually occurs)

Or is that portion of it done manually by a maintainer?

**Comment by mosabua** [comment]
The build for the release is done by @martint typically as part of the release - scripts are in the release-scripts repo .. 

For trino-gateway I think we want a similar maven module setup that runs as part of the build but the scripts for the release will also be in this same trino-gateway repo

**Comment by mosabua** [comment]
Also see https://github.com/trinodb/release-scripts/blob/master/trino-docker.sh

**Comment by mosabua** [comment]
Duplicate of #48

**Comment by mosabua** [comment]
We could also consider reviving a docker compose setup that we removed with https://github.com/trinodb/trino-gateway/pull/146/files .. if users desire that.

**Comment by mosabua** [comment]
All done with release 6.

**Comment by mosabua** [comment]
Also includes work in 

* #198 
* #227 
* #209
